application: pycashexdev
version: 1017
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: '30d'

builtins:
- remote_api: on

inbound_services:
- warmup

libraries:
- name: django
  version: latest
- name: lxml
  version: latest

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.jar
- ^(.*/)?.settings/.*
- ^(.*/)?.git/.*
    
handlers:
- url: /_ah/queue/deferred
  script: djangoappengine.deferred.handler.application
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine.appstats.application
  login: admin
    
- url: /_ah/warmup
  script: warmup.app
  login: admin
  
- url: /media/admin
  static_dir: django/contrib/admin/media

- url: /media/mobile/lib
  static_dir: pycash/static/mobile/lib
  
- url: /media
  static_dir: pycash/static
  expiration: '7d'
  
- url: /cron/.*
  script: djangoappengine.main.application
  login: admin
  
- url: /favicon.ico
  static_files: pycash/static/images/favicon.ico
  upload: pycash/static/images/favicon.ico

- url: /robots.txt
  static_files: pycash/static/robots.txt
  upload: pycash/static/robots.txt
  
- url: /(.*\.(gif|png|jpg))
  static_dir: pycash/static/images
  
- url: /.*
  script: djangoappengine.main.application
  secure: always
